apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wojkji5qi-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wojkji5qi-nodejs 
  name: wojkji5qi-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wojkji5qi-nodejs 
